### ISSUE TITLE
turboboost form with uploads submit, but newly rendered pages don't show

### ISSUE THREAD

**Issue by yomna-fahmy** [waymondo/turboboost#11]
Using rails 4.2.1, turboboost 0.0.12, remotipart 1.2.1, carrierwave and carrierwave_backgrounder

When submitting the form without uploading any file, everything works fine.
But when submitting with uploads, the server renders the correct page but the browser keeps showing the form (with the form submit button disabled)

<%= form_for company, url: registration_path(resource_name), html: { multipart: true }, validate: true, turboboost: true do |f| %>

request.headers['HTTP_X_TURBOBOOST'] is not set

**Comment by waymondo** [comment]
I'll check this out. Where is the `validate: true` coming from?

**Comment by francesco-loreti** [comment]
I have same problem but I can't use attribute validate in my form.

**Comment by yomna-fahmy** [comment]
We are using https://github.com/DavyJonesLocker/client_side_validations

**Comment by simonini** [comment]
I have same problem with same configuration (rails 4.2, turbobootst 0.0.0.12, remotipart 1.2.1)

```
= form_for Image.new, turboboost: true, :html => { :multipart => true } do |f|
      = f.file_field :url
      = f.submit 'Send'

**Comment by francesco-loreti** [comment]
In my application the turboboost not work with form or link that have attribute "multipart: true" or "remote:true". In the first case not work the form when I add one file, in the second case execute action but don't execute the js respond...

**Comment by waymondo** [comment]
Thanks for noting this - I will try to check it out in the next few days once things calm down at work.

**Comment by waymondo** [comment]
Sorry for the delay on this. 

I spent some time looking into how `remotipart` works and it doesn't look like it will jive seamlessly with `turboboost`. If `remotipart` notices a file input in a multipart form, it will hijack and [cancel the form's AJAX request](https://github.com/JangoSteve/remotipart/blob/master/vendor/assets/javascripts/jquery.remotipart.js#L62) and send the form through a hidden `iframe`, which unsets the `X-Turboboost` header. Also, it [overrides the render method](https://github.com/JangoSteve/remotipart/blob/master/lib/remotipart/render_overrides.rb#L13-L21) by mutating the response into a textarea, which won't work for the partial response rendering options. Handling all of these custom cases for supporting this one gem isn't something I feel up to incorporating and supporting.

The good news is, it seems simple enough to use them separately in the following way.

If your form looks like this:

`<%= form_for company, turboboost: true, html: { multipart: true } do |f| %>`

You can have a controller that reacts to `remotipart_submitted?` in the `js` handler.

```
class CompaniesController < ApplicationController
  def create
    @company = Company.create!(company_params)
    respond_to do |format|
      format.html { redirect_to @company, notice: 'Company was successfully updated.' }
      format.js do
        unless remotipart_submitted?
          redirect_to @company, notice: 'Company was successfully created.'
        end
      end
    end
  end
end
```

If the action is hit without `remotipart`, `turboboost` will work like normal. Otherwise, you can just create `app/views/posts/create.js.erb` and add:

```
Turbolinks.visit("<%= company_url(@company) %>");
```

Which would simulate the same redirection effectively. You could use the same pattern to simulate a partial DOM update as well.

**Comment by waymondo** [comment]
Since I haven't heard back from anyone regarding the research and solution I posted above, I'm closing this.

**Comment by vanoushka** [comment]
I'm having the same issue @francesco-loreti described, and I'm not using remotipart, when I submit a multipart form without a file it works fine, but when I set a file the redirection isn't handled by turbolinks.
