### ISSUE TITLE
jQuery being included again

### ISSUE THREAD

**Issue by archonic** [waymondo/turboboost#6]
Trying to narrow down why jQuery plugins weren't working for me, I found that `//= require turboboost` is including jQuery after it's already been included. With turboboost being the only `//= require` in my application.js, this is the output in the `<head>` in development.

    <script src="/assets/jquery-eb3e278249152b5b5d5170b73d9dbf52.js?body=1" data-turbolinks-track="true"></script>
    <script src="/assets/jquery-eb3e278249152b5b5d5170b73d9dbf52.js?body=1" data-turbolinks-track="true"></script>
    <script src="/assets/jquery_ujs-0b8f09cf5aec4ba1be1abd9f915c77e2.js?body=1" data-turbolinks-track="true"></script>
    <script src="/assets/turbolinks-924184401b7d116eadaaefc96895fa84.js?body=1" data-turbolinks-track="true"></script>
    <script src="/assets/turboboost-11586472b2a422a2e462fbc0a8c1648f.js?body=1" data-turbolinks-track="true"></script>
    <script src="/assets/application-44b7eb0053882cac794afe54eefa1a15.js?body=1" data-turbolinks-track="true"></script>

**Comment by waymondo** [comment]
I just created a fresh Rails 4.2 app with turboboost and only `//= require turboboost` in application.js and jQuery is only included once. Even if have an application.js that looks like this:

```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require turboboost
```

jQuery will only be included once because of how the [require directive](https://github.com/sstephenson/sprockets#the-require-directive) works. Something else is going on in your app.

What does your `<head>` markup look like? Do you have `require_tree` in your `application.js`? Other asset gems?

**Comment by archonic** [comment]
Yes, I have `require_tree`. I eventually found that the surveyor gem generator made a file called `surveyor_all.js` which was requiring jquery a second time. My bad and thanks for the help!
