### ISSUE TITLE
jQuery inclusion

### ISSUE THREAD

**Issue by agios** [waymondo/turboboost#8]
I was wondering if there is a specific reason that turboboost.js forces the require of jquery etc?

This makes it problematic if eg you intended to include jquery from a CDN. Maybe instead of including them directly, it might be more flexible to just add a note to the README specifying that they are required and leave it to each developer to handle it on a per application case?

**Comment by waymondo** [comment]
Ideally, one day I will update the Turboboost script so that it doesn't depend on jQuery, but it was easiest for me to rely on it when I originally wrote the gem. For now though, I separated out the script manifest from the Turboboost script itself so you can do what you are requesting. Readme is updated
